title: Lee SuBum
logo: /bumwhale.png
email: solbum0418@kookmin.ac.kr
description: Hello? This is my Blog
favicon: true
color-scheme: auto

comments:
    provider: disqus
    disqus:         
        shortname: bumwhale

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/solbum
  - name: Comment
    link: https://solbum.github.io/another-page.html

url: https://solbum.github.io